env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  #  - plugin:prettier/recommended
  - plugin:svelte/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  #  project: "./tsconfig.json"
  extraFileExtensions: [".svelte"]
overrides:
  [
    {
      files: ["*.svelte"],
      parser: "svelte-eslint-parser",
      parserOptions:
        {
          parser:
            {
              ts: "@typescript-eslint/parser",
              js: "espree",
              typescript: "@typescript-eslint/parser",
            },
        },
    },
  ]
plugins:
  - "@typescript-eslint"
  - "svelte"
# eslint側でwaningを無視する(a11y系warning対策) 同様に $ npm run check に --compiler-warnings オプションを追加
rules: { svelte/valid-compile: ["error", { ignoreWarnings: true }] }
